# -*- coding: utf-8 -*-
"""
Generate bilingual HTML knowledge base report.
Usage: python gen_report.py        → generates report_cn.html + report_en.html
       python gen_report.py --cn    → Chinese only
       python gen_report.py --en    → English only
       Double-click the .html file to view in browser — no Python needed!
"""
import sqlite3, os, json, sys
from datetime import datetime

DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data', 'species.db')
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data', 'reports')

# ── Bilingual labels ──
L = {
    'cn': {
        'title': '三生万物 · 长江鱼类知识库',
        'subtitle': 'SanShengWanWu · Yangtze Fish Knowledge Base',
        'species': '物种名录',
        'traits': '性状数据库',
        'literature': '文献数据库',
        'sources': '数据来源',
        'stats': '统计总览',
        'chinese_name': '中文名',
        'scientific_name': '学名',
        'family': '科',
        'conservation': '保护等级',
        'feeding': '食性与营养',
        'migration': '洄游',
        'conservation_status': '保护等级',
        'morphology': '形态特征',
        'trophic_level': '营养级',
        'feeding_type': '食性类型',
        'predation_strategy': '捕食策略',
        'migration_type': '洄游类型',
        'migration_distance': '洄游距离',
        'iucn': 'IUCN',
        'china_red_list': '中国红色名录',
        'population_trend': '种群趋势',
        'threats': '主要威胁',
        'max_length': '最大体长',
        'common_length': '常见体长',
        'max_weight': '最大体重',
        'body_shape': '体形',
        'mouth_position': '口位',
        'scale_type': '鳞型',
        'source': '数据来源',
        'confidence': '置信度',
        'year': '年份',
        'journal': '期刊',
        'total_species': '物种总数',
        'total_traits': '性状记录',
        'total_literature': '文献总数',
        'total_sources': '数据来源数',
        'footer': f'由三生万物生态系统自动生成 · {datetime.now().strftime("%Y-%m-%d %H:%M")}',
        'notes': '备注',
        'diet_shift': '食性转换',
        'barrier_sensitivity': '水坝敏感性',
        'commercial': '经济价值',
        'synonyms': '分类变更与异名',
        'accepted_name': '接受名',
        'synonym_name': '异名/旧名',
        'synonym_type': '类型',
        'change_reason': '变更原因',
    },
    'en': {
        'title': 'SanShengWanWu · Yangtze Fish Knowledge Base',
        'subtitle': 'Together infinite power, apart top expert engines',
        'species': 'Species Catalog',
        'traits': 'Trait Database',
        'literature': 'Literature Database',
        'sources': 'Data Sources',
        'stats': 'Statistics Overview',
        'chinese_name': 'Chinese Name',
        'scientific_name': 'Scientific Name',
        'family': 'Family',
        'conservation': 'Conservation',
        'feeding': 'Feeding & Trophic Ecology',
        'migration': 'Migration',
        'conservation_status': 'Conservation Status',
        'morphology': 'Morphology',
        'trophic_level': 'Trophic Level',
        'feeding_type': 'Feeding Type',
        'predation_strategy': 'Predation Strategy',
        'migration_type': 'Migration Type',
        'migration_distance': 'Migration Distance',
        'iucn': 'IUCN',
        'china_red_list': 'China Red List',
        'population_trend': 'Population Trend',
        'threats': 'Major Threats',
        'max_length': 'Max Length',
        'common_length': 'Common Length',
        'max_weight': 'Max Weight',
        'body_shape': 'Body Shape',
        'mouth_position': 'Mouth Position',
        'scale_type': 'Scale Type',
        'source': 'Source',
        'confidence': 'Confidence',
        'year': 'Year',
        'journal': 'Journal',
        'total_species': 'Total Species',
        'total_traits': 'Trait Records',
        'total_literature': 'Literature Records',
        'total_sources': 'Data Sources',
        'footer': f'Generated by SanShengWanWu Ecosystem · {datetime.now().strftime("%Y-%m-%d %H:%M")}',
        'notes': 'Notes',
        'diet_shift': 'Diet Shift',
        'barrier_sensitivity': 'Barrier Sensitivity',
        'commercial': 'Commercial Value',
        'synonyms': 'Taxonomic Synonyms & Changes',
        'accepted_name': 'Accepted Name',
        'synonym_name': 'Synonym/Old Name',
        'synonym_type': 'Type',
        'change_reason': 'Reason for Change',
    }
}

# ── Read database ──
db = sqlite3.connect(DB)
db.row_factory = sqlite3.Row

species_list = [dict(r) for r in db.execute("SELECT * FROM species ORDER BY chinese")]
trait_data = {}
for table in ['traits_feeding','traits_migration','traits_conservation','traits_morphology']:
    rows = db.execute(f"SELECT * FROM {table}").fetchall()
    if rows:
        trait_data[table] = [dict(r) for r in rows]

literature_list = [dict(r) for r in db.execute("SELECT * FROM literature ORDER BY year DESC")]
sources_list = [dict(r) for r in db.execute("SELECT * FROM trait_sources ORDER BY reliability DESC")]
synonym_list = [dict(r) for r in db.execute("SELECT * FROM taxonomic_synonyms ORDER BY accepted_name")]

stats = {
    'species': len(species_list),
    'traits': sum(len(v) for v in trait_data.values()),
    'literature': len(literature_list),
    'sources': len(sources_list),
    'synonyms': len(synonym_list),
}
db.close()


def generate(lang):
    """Generate HTML report in given language."""
    T = L[lang]
    lang_attr = 'zh-CN' if lang == 'cn' else 'en'

    # Conservation color coding
    def cons_color(s):
        s = (s or '').upper()
        if 'CR' in s or '极危' in s: return '#d32f2f'
        if 'EN' in s or '濒危' in s: return '#f57c00'
        if 'VU' in s or '易危' in s: return '#fbc02d'
        if 'NT' in s or '近危' in s: return '#388e3c'
        if 'LC' in s or '无危' in s: return '#2e7d32'
        return '#999'

    def confidence_stars(n):
        n = n or 3
        return '★' * n + '☆' * (5 - n)

    # ── Build HTML ──
    html = f'''<!DOCTYPE html>
<html lang="{lang_attr}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{T['title']}</title>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family: 'Segoe UI', 'Microsoft YaHei', sans-serif; background:#f5f7fa; color:#333; line-height:1.6; }}
.header {{ background:linear-gradient(135deg,#1a237e,#283593); color:white; padding:40px 20px; text-align:center; }}
.header h1 {{ font-size:2em; margin-bottom:8px; }}
.header p {{ opacity:0.85; font-size:1.1em; }}
.container {{ max-width:1200px; margin:0 auto; padding:20px; }}
.card {{ background:white; border-radius:12px; box-shadow:0 2px 12px rgba(0,0,0,0.08); margin-bottom:24px; overflow:hidden; }}
.card-header {{ background:#f0f2f5; padding:16px 24px; font-size:1.2em; font-weight:700; border-bottom:1px solid #e0e0e0; }}
.card-body {{ padding:20px 24px; }}
table {{ width:100%; border-collapse:collapse; }}
th {{ background:#f5f5f5; padding:12px 14px; text-align:left; font-weight:600; border-bottom:2px solid #ddd; white-space:nowrap; }}
td {{ padding:10px 14px; border-bottom:1px solid #eee; }}
tr:hover {{ background:#fafbfc; }}
.badge {{ display:inline-block; padding:2px 10px; border-radius:12px; font-size:0.85em; font-weight:600; color:white; }}
.stats-grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:16px; }}
.stat-card {{ background:white; border-radius:12px; padding:20px; text-align:center; box-shadow:0 1px 6px rgba(0,0,0,0.06); }}
.stat-card .num {{ font-size:2.5em; font-weight:800; color:#1a237e; }}
.stat-card .label {{ color:#666; margin-top:4px; }}
.trait-block {{ margin-bottom:20px; padding:16px; background:#fafbfc; border-radius:8px; border-left:4px solid #1a237e; }}
.trait-block h3 {{ color:#1a237e; margin-bottom:8px; }}
.trait-grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(280px,1fr)); gap:8px; }}
.trait-item {{ padding:6px 0; }}
.trait-key {{ color:#666; font-size:0.9em; }}
.trait-val {{ font-weight:500; }}
.footer {{ text-align:center; padding:30px; color:#999; font-size:0.9em; }}
.source-card {{ display:flex; align-items:center; gap:12px; padding:12px 0; border-bottom:1px solid #f0f0f0; }}
.source-stars {{ color:#f9a825; font-size:1.1em; min-width:80px; }}
.source-info {{ flex:1; }}
.source-name {{ font-weight:600; }}
.source-meta {{ color:#888; font-size:0.85em; }}
</style>
</head>
<body>

<div class="header">
  <h1>{T['title']}</h1>
  <p>{T['subtitle']}</p>
</div>

<div class="container">

<!-- Stats -->
<div class="stats-grid">
  <div class="stat-card"><div class="num">{stats['species']}</div><div class="label">{T['total_species']}</div></div>
  <div class="stat-card"><div class="num">{stats['traits']}</div><div class="label">{T['total_traits']}</div></div>
  <div class="stat-card"><div class="num">{stats['literature']}</div><div class="label">{T['total_literature']}</div></div>
  <div class="stat-card"><div class="num">{stats['sources']}</div><div class="label">{T['total_sources']}</div></div>
</div>

<!-- Species Catalog -->
<div class="card">
<div class="card-header">📋 {T['species']} ({len(species_list)})</div>
<div class="card-body" style="overflow-x:auto;">
<table>
<thead><tr>
  <th>{T['chinese_name']}</th><th>{T['scientific_name']}</th>
  <th>{T['family']}</th><th>{T['conservation']}</th>
</tr></thead>
<tbody>'''

    for sp in species_list:
        cn = sp.get('chinese', '')
        sn = sp.get('scientific', '')
        en = sp.get('name_en', '')
        fm = sp.get('family', '')
        cs = sp.get('conservation', '') or '-'
        color = cons_color(cs)
        html += f'<tr><td><strong>{cn}</strong>{(" <br><small style=\"color:#888\">" + en + "</small>") if en else ""}</td><td><em>{sn}</em></td>'
        html += f'<td>{fm}</td>'
        html += f'<td><span class="badge" style="background:{color}">{cs}</span></td></tr>\n'

    html += '</tbody></table></div></div>\n'

    # Trait Database
    trait_labels = {
        'traits_morphology': T['morphology'],
        'traits_feeding': T['feeding'],
        'traits_migration': T['migration'],
        'traits_conservation': T['conservation_status'],
    }
    html += f'<div class="card"><div class="card-header">🔬 {T["traits"]} ({stats["traits"]})</div><div class="card-body">\n'

    for table, label in trait_labels.items():
        rows = trait_data.get(table, [])
        if not rows:
            continue
        html += f'<h3 style="margin:16px 0 8px;color:#1a237e;">{label} ({len(rows)})</h3>\n'
        for r in rows:
            sid = r.get('species_id', '?')
            html += f'<div class="trait-block"><strong>{sid}</strong>'
            html += '<div class="trait-grid">'
            for k, v in r.items():
                if k in ('id', 'species_id') or v is None or v == '':
                    continue
                if k == 'confidence':
                    html += f'<div class="trait-item"><span class="trait-key">{T["confidence"]}:</span> <span class="trait-val">{confidence_stars(v)}</span></div>'
                elif k == 'source':
                    html += f'<div class="trait-item"><span class="trait-key">{T["source"]}:</span> <span class="trait-val">{v}</span></div>'
                else:
                    html += f'<div class="trait-item"><span class="trait-key">{k}:</span> <span class="trait-val">{v}</span></div>'
            html += '</div></div>\n'
    html += '</div></div>\n'

    # Literature
    html += f'<div class="card"><div class="card-header">📚 {T["literature"]} ({len(literature_list)})</div><div class="card-body">\n'
    for lit in literature_list:
        yr = lit.get('year', '?')
        title = lit.get('title', '')[:100]
        journal = lit.get('journal', '')
        sid = lit.get('species_id', '')
        html += f'<div style="padding:10px 0;border-bottom:1px solid #f0f0f0;">'
        html += f'<strong>[{yr}]</strong> <em>{title}</em><br>'
        html += f'<span style="color:#888;">{journal}</span> · <span style="color:#1a237e;">{sid}</span>'
        html += '</div>\n'
    html += '</div></div>\n'

    # Data Sources
    html += f'<div class="card"><div class="card-header">📡 {T["sources"]} ({len(sources_list)})</div><div class="card-body">\n'
    for s in sources_list:
        stars = confidence_stars(s.get('reliability', 3))
        name = s.get('source_name', '')
        stype = s.get('source_type', '')
        freq = s.get('update_frequency', '')
        html += f'<div class="source-card">'
        html += f'<div class="source-stars">{stars}</div>'
        html += f'<div class="source-info"><div class="source-name">{name}</div>'
        html += f'<div class="source-meta">{stype} · {freq}</div></div>'
        html += '</div>\n'
    html += '</div></div>\n'

    # Taxonomic Synonyms
    html += f'<div class="card"><div class="card-header">🔄 {T["synonyms"]} ({len(synonym_list)})</div><div class="card-body" style="overflow-x:auto;">\n'
    html += '<table><thead><tr>'
    html += f'<th>{T["accepted_name"]}</th><th>{T["synonym_name"]}</th><th>{T["synonym_type"]}</th><th>{T["change_reason"]}</th>'
    html += '</tr></thead><tbody>\n'
    for s in synonym_list:
        acc = s.get('accepted_name', '')
        syn = s.get('synonym', '')
        stype = s.get('synonym_type', '')
        reason = s.get('reason', '')[:100]
        stype_badge = {'junior': '#e65100', 'misspelling': '#6a1b9a', 'alternate': '#1565c0', 'accepted': '#2e7d32'}.get(stype, '#999')
        html += f'<tr><td><em>{acc}</em></td><td><em>{syn}</em></td>'
        html += f'<td><span class="badge" style="background:{stype_badge}">{stype}</span></td>'
        html += f'<td>{reason}</td></tr>\n'
    html += '</tbody></table></div></div>\n'

    # Footer
    html += f'<div class="footer">{T["footer"]}</div>\n</div>\n</body>\n</html>'

    return html


# ── Main ──
if __name__ == '__main__':
    do_cn = '--en' not in sys.argv
    do_en = '--cn' not in sys.argv

    if do_cn:
        path_cn = os.path.join(OUT_DIR, 'report_cn.html')
        with open(path_cn, 'w', encoding='utf-8') as f:
            f.write(generate('cn'))
        print(f'Chinese report: {path_cn}')

    if do_en:
        path_en = os.path.join(OUT_DIR, 'report_en.html')
        with open(path_en, 'w', encoding='utf-8') as f:
            f.write(generate('en'))
        print(f'English report: {path_en}')

    print('\nDouble-click the .html file to view in your browser!')
